default: &default
  split_design_documents_per_view: true # optional

development:
  <<: *default
  database: merkado_development
test:
  <<: *default
  database: merkado_test
production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
